### ISSUE TITLE
ValueError: No individual observed for the SNP

### ISSUE THREAD

**Issue by snowformatics** [fastlmm/FaST-LMM#35]
Hello,

I am using fast-lmm since long time but for first time I see this error. Genotypes and phenotypes are loaded and the analysis starts but after some running time, this error appears:

`Traceback (most recent call last):
  File "C:/Users/X/PycharmProjects/Genomics/Projects/X/WCC/wcc_pipeline.py", line 39, in <module>
    path + pheno, pheno.split('.')[0] + 'wgs.csv', sep=';', cov=False)
  File "C:\Users\X\PycharmProjects\Genomics\gwas_class.py", line 18, in gwas_fast_lmm
    gwas_results = single_snp(geno, pheno)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 379, in single_snp
    runner=runner_outer,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 202, in map_reduce
    result = runner.run(dist)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\local.py", line 48, in run
    result = _run_all_in_memory(distributable)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 30, in _run_all_in_memory
    return work.reduce(result_sequence)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 77, in reduce
    return self.reducer(output_seq)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 358, in reducer_closure
    frame = pd.concat(frame_sequence)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\core\reshape\concat.py", line 304, in concat
    sort=sort,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\core\reshape\concat.py", line 348, in __init__
    objs = list(objs)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 14, in work_sequence_to_result_sequence
    result = work()
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 65, in <lambda>
    yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg)  # the 'i=i',etc is need to get around a strangeness in Python
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 92, in dowork
    result = _run_all_in_memory(work)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 25, in _run_all_in_memory
    return work()
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 91, in <lambda>
    work = lambda : self.mapper(input_arg)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 352, in nested_closure
    xp=xp,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 922, in _internal_single
    runner,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 1069, in _find_h2_s_u
    xp,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 1188, in _find_h2_s_u_for_one_pheno
    xp=xp,
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 701, in combine_the_best_way
    to_kerneldata=True, return_trained=True
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\kernelreader\snpkernel.py", line 120, in _read_with_standardizing
    val, snp_trained = self.snpreader._read_kernel(self.standardizer,block_size=self.block_size,return_trained=True,num_threads=num_threads)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpreader.py", line 653, in _read_kernel
    train_data,trained_standardizer = SnpReader._as_snpdata(self[:,start:start+block_size],standardizer=standardizer,dtype=dtype,order='A',force_python_only=force_python_only, num_threads=num_threads)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpreader.py", line 621, in _as_snpdata
    return snpreader.read(order=order,dtype=dtype).standardize(standardizer,return_trained=True,force_python_only=force_python_only,num_threads=num_threads)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpdata.py", line 184, in standardize
    _, trained = standardizer.standardize(self, return_trained=True, force_python_only=force_python_only, num_threads=num_threads)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\standardizer\unit.py", line 45, in standardize
    use_stats=False,stats=None,num_threads=num_threads, force_python_only=force_python_only)
  File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\standardizer\standardizer.py", line 114, in _standardize_unit_and_beta
    standardize_f64(snps,is_beta,a,b,apply_in_place,use_stats,stats,num_threads)
ValueError: No individual observed for the SNP.
`

System: Windows 10. Python 3.7, fastlmm 0.6.1

I checked both files and they seems to be fine, nothing special. Does anybody has an idea what could be the problem?

Thanks

**Comment by CarlKCarlK** [comment]
Greetings,

Thanks for your continued use of FaST-LMM!

The message comes from our BED reading software when it finds a SNP with no non-missing data. Likely causes:

  *   A SNP with all missing data
  *   The SNP data and the other data files (phenotype, covariate) have mis-matched IIDs, so when FaST-LMM finds the individuals common to all of them, the number is zero (or very small and that small number has all missing SNP data).

If this isn't enough info for you to find the problem, tell me about your inputs file (what kinds and about how big) and I send you a Python script that you can run that will pinpoint the problem.)

Yours,
Carl


From: snowformatics ***@***.***>
Sent: Monday, June 5, 2023 5:18 AM
To: fastlmm/FaST-LMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/FaST-LMM] ValueError: No individual observed for the SNP (Issue #35)
Importance: High


Hello,

I am using fast-lmm since long time but for first time I see this error. Genotypes and phenotypes are loaded and the analysis starts but after some running time, this error appears:

Traceback (most recent call last): File "C:/Users/X/PycharmProjects/Genomics/Projects/X/WCC/wcc_pipeline.py", line 39, in <module> path + pheno, pheno.split('.')[0] + 'wgs.csv', sep=';', cov=False) File "C:\Users\X\PycharmProjects\Genomics\gwas_class.py", line 18, in gwas_fast_lmm gwas_results = single_snp(geno, pheno) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 379, in single_snp runner=runner_outer, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 202, in map_reduce result = runner.run(dist) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\local.py", line 48, in run result = _run_all_in_memory(distributable) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 30, in _run_all_in_memory return work.reduce(result_sequence) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 77, in reduce return self.reducer(output_seq) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 358, in reducer_closure frame = pd.concat(frame_sequence) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper return func(*args, **kwargs) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\core\reshape\concat.py", line 304, in concat sort=sort, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pandas\core\reshape\concat.py", line 348, in __init__ objs = list(objs) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 14, in work_sequence_to_result_sequence result = work() File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 65, in <lambda> yield lambda i=i, input_arg=input_arg: self.dowork(i, input_arg) # the 'i=i',etc is need to get around a strangeness in Python File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 92, in dowork result = _run_all_in_memory(work) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\runner\__init__.py", line 25, in _run_all_in_memory return work() File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\util\mapreduce1\mapreduce.py", line 91, in <lambda> work = lambda : self.mapper(input_arg) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 352, in nested_closure xp=xp, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 922, in _internal_single runner, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 1069, in _find_h2_s_u xp, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 1188, in _find_h2_s_u_for_one_pheno xp=xp, File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\fastlmm\association\single_snp.py", line 701, in combine_the_best_way to_kerneldata=True, return_trained=True File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\kernelreader\snpkernel.py", line 120, in _read_with_standardizing val, snp_trained = self.snpreader._read_kernel(self.standardizer,block_size=self.block_size,return_trained=True,num_threads=num_threads) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpreader.py", line 653, in _read_kernel train_data,trained_standardizer = SnpReader._as_snpdata(self[:,start:start+block_size],standardizer=standardizer,dtype=dtype,order='A',force_python_only=force_python_only, num_threads=num_threads) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpreader.py", line 621, in _as_snpdata return snpreader.read(order=order,dtype=dtype).standardize(standardizer,return_trained=True,force_python_only=force_python_only,num_threads=num_threads) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\snpreader\snpdata.py", line 184, in standardize _, trained = standardizer.standardize(self, return_trained=True, force_python_only=force_python_only, num_threads=num_threads) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\standardizer\unit.py", line 45, in standardize use_stats=False,stats=None,num_threads=num_threads, force_python_only=force_python_only) File "C:\Users\X\Anaconda3\envs\genomics_env\lib\site-packages\pysnptools\standardizer\standardizer.py", line 114, in _standardize_unit_and_beta standardize_f64(snps,is_beta,a,b,apply_in_place,use_stats,stats,num_threads) ValueError: No individual observed for the SNP.

I checked both files and they seems to be fine, nothing special. Does anybody has an idea what could be the problem?

Thanks

-

**Comment by snowformatics** [comment]
Hi Carl,

thanks for your reply and maintaining fast-lmm. It's the most frequent and favorite Python library (besides numpy) :)

I checked the phenotype and fam IDs and could not see a problem, also I quickly run a glm with Plink which was fine. I would appreciate a lot if you could sent me the Python script to find out what is going on. In addition, I will sent you some sample files (can not post here they are confidential).

I would like to sent you a coffee (or beer) donation, 
Thanks again for your efforts

**Comment by CarlKCarlK** [comment]
import numpy as np
from pathlib import Path
from pysnptools.snpreader import Bed, Pheno
import pysnptools.util as pstutil
from fastlmm.association import single_snp

root = Path("C:\\deldir\\test_carl")
bed_file = root / "090222_8070_test.bed"
pheno_file = root / "pheno.csv"

bed = Bed(str(bed_file), count_A1=False)
pheno = Pheno(str(pheno_file))
print(bed.iid_count, bed.sid_count, pheno.iid_count)

# create a bed file with only the individuals that are in both the bed and pheno files
bed2, pheno2 = pstutil.intersect_apply([bed, pheno])
print(bed2.iid_count, pheno2.iid_count)

# read the values from that bed file
bed2_val = bed2.read().val

# find the columns that are all NaN (missing)
all_nan = np.isnan(bed2_val).all(axis=0)
# print the number of all NaN columns
print(np.sum(all_nan))
# print the names of the SNPs that are all NaN
print(bed2.sid[all_nan])
# remove these SNPs from consideration
bed2_fixed = bed2[:, ~all_nan]

print(bed2_fixed.iid_count, bed2_fixed.sid_count)

# Optional: write bed2_fixed to a new file
# bed2_fixed.write("fixed.bed", count_A1=False)

# run single_snp with the fixed file
single_snp(bed2_fixed, pheno2, output_file_name="single_snp.csv")

**Comment by CarlKCarlK** [comment]
Here is an explanation and a fix.

In this case, the pheno file contained 445 individuals. If we look only at those individuals’ Bed data, then 33 of the SNPs are missing all data.
 
The script below finds the all-missing-SNPs and then removes them from consideration.

[If in the future, someone tries this and it doesn't work then the likely causes are: you need to consider a covariate file, also, or the script runs out of memory. If this happens, let me know, the script can be enhanced to use covariates files and to use less memory.]


```
import numpy as np
from pathlib import Path
from pysnptools.snpreader import Bed, Pheno
import pysnptools.util as pstutil
from fastlmm.association import single_snp

root = Path("C:\\deldir\\test_carl")
bed_file = root / "test.bed"
pheno_file = root / "pheno.csv"

bed = Bed(str(bed_file), count_A1=False)
pheno = Pheno(str(pheno_file))
print(bed.iid_count, bed.sid_count, pheno.iid_count)

# create a bed file with only the individuals that are in both the bed and pheno files
bed2, pheno2 = pstutil.intersect_apply([bed, pheno])
print(bed2.iid_count, pheno2.iid_count)

# read the values from that bed file
bed2_val = bed2.read().val

# find the columns that are all NaN (missing)
all_nan = np.isnan(bed2_val).all(axis=0)
# print the number of all NaN columns
print(np.sum(all_nan))
# print the names of the SNPs that are all NaN
print(bed2.sid[all_nan])
# remove these SNPs from consideration
bed2_fixed = bed2[:, ~all_nan]

print(bed2_fixed.iid_count, bed2_fixed.sid_count)

# Optional: write bed2_fixed to a new file
# bed2_fixed.write("fixed.bed", count_A1=False)

# run single_snp with the fixed file
# single_snp(bed2_fixed, pheno2, output_file_name="single_snp.csv")
```

**Comment by CarlKCarlK** [comment]
Here is a version of the code that removes SNPs from consideration if they are empty (after intersecting with phen data). It uses less memory than the previous version.

```
import numpy as np
from pathlib import Path
import logging
from pysnptools.snpreader import Bed, Pheno
import pysnptools.util as pstutil
from pysnptools.util import log_in_place
from fastlmm.association import single_snp

# turn on logging to INFO level
logging.basicConfig(level=logging.INFO)

root = Path("C:\\deldir\\test_carl")
bed_file = root / "test.bed"
pheno_file = root / "pheno.csv"
sid_batch_size = 1000 # number of SNPs to read at a time


def filter_out_missing(bed, pheno):
    # list of all NaN columns
    all_nan = []

    with log_in_place("read snp #", logging.INFO) as updater:
        for sid_start in range(0, bed.sid_count, sid_batch_size):
            updater(f"sid {sid_start:,} of {bed.sid_count:,}")

            # read a batch of SNPs
            snp_data_batch = bed[:, sid_start:sid_start+sid_batch_size].read()
            # find the columns that are all NaN (missing)
            nan_in_batch = np.isnan(snp_data_batch.val).all(axis=0)
            all_nan.append(nan_in_batch)
    # concatenate the list of all NaN columns into a single boolean array
    all_nan = np.concatenate(all_nan, axis=0)

    # print the number of all NaN columns
    logging.info(f"number of all missing columns is {np.sum(all_nan):,}. They are: ")
    logging.info(bed.sid[all_nan])

    # remove these SNPs from consideration
    bed_fixed = bed[:, ~all_nan]

    return bed_fixed

bed = Bed(str(bed_file), count_A1=False)
pheno = Pheno(str(pheno_file))
print(f"Before, bed is {bed.iid_count:,} x {bed.sid_count:,}, pheno is {pheno.iid_count:,}")

# replace original bed with one that has the same iids as the pheno
bed, pheno = pstutil.intersect_apply([bed, pheno])
print(f"After intersection, bed is {bed.iid_count} x {bed.sid_count:,}, pheno is {pheno.iid_count:,}")

bed_fixed = filter_out_missing(bed, pheno)
# format numbers with commas and no decimals

print(f"After removing missing, bed is {bed.iid_count:,} x {bed.sid_count:,}, pheno is {pheno.iid_count:,}")


# run single_snp with the fixed file
# single_snp(bed_fixed, pheno, output_file_name="single_snp.csv")
```
